--●主页●
drawerLayout.getChildAt(0).addView(loadlayout{
  id="ggw";
  LinearLayout;
  orientation="vertical";--垂直
  layout_width="fill";--布局宽度
  layout_height="fill";--布局高度
  {--███全局竖向滑动███
    ScrollView;--竖向滑动
    layout_width="fill";--宽
    layout_height="fill";--滑动范围高度
    background="#FFFFFFFF";--颜色
    layout_marginTop="104%w";--顶距

    {--●广告●
      LinearLayout;
      orientation="horizontal";--水平
      layout_width="fill";
      layout_height="fill";
      layout_margin="3%w";--边距
      layout_marginTop="0%w";--顶距
      background="#00000000";--颜色
      {--◆左◆
        LinearLayout;
        layout_weight="1";--权重
        layout_height="fill";--高度
        orientation="vertical";--重力
        layout_marginRight="1.25%w";--右距
        {--◆A
          LinearLayout;
          orientation="vertical";--垂直
          layout_width="fill";--宽度
          layout_height="175dp";--高度
          layout_marginBottom="2.5%w";--底距
          {--卡片布局
            CardView;
            radius="55";--圆角
            elevation="0";--阴影
            layout_width="fill";--宽度
            layout_height="fill";--高度
            CardBackgroundColor="#AEEEEEEE";
            {--◇主图
              ImageView;--图片控件
              layout_width="175dp";--宽度
              layout_height="fill";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background="https://txc.gtimg.com/data/292760/2024/0713/a71e8600432e1031ccd5b303357d86f3.webp";
            },--主图◇
            {--◇标题
              TextView;
              text="会下雨的生态缸";
              textSize="15sp";
              textColor="#FFFFFFFF";--颜色
              background='#60000000',--背景色
              layout_width="fill";--宽度
              layout_height="28dp";--高度
              --layout_margin="3.5dp";--边距
              layout_gravity="bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接="https://shop420102691.m.taobao.com/"})
            end;
          },--卡片布局
        },--A◆
        {--◆B
          CardView;--卡片控件
          radius="55";--圆角
          elevation="0";--阴影
          layout_width="fill";--宽度
          layout_height="255dp";--高度
          layout_marginBottom="2.5%w";--底距
          CardBackgroundColor="#AEEEEEEE";
          {--竖直布局
            LinearLayout;
            layout_width="fill";--宽度
            layout_height="fill";--高度
            orientation="vertical";--重力
            {--◇主图
              ImageView;--图片控件
              layout_width="170dp";--宽度
              layout_height="227dp";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background=图B;
            },--主图◇
            {--◇标题
              TextView;
              text=标B;
              textSize="15sp";
              textColor="#FF333333";
              layout_width="160dp";--宽度
              layout_margin="3.5dp";--边距
              layout_gravity="bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接=链B})
            end;
          },--竖直布局
        },--B◆
        {--◆C
          LinearLayout;
          layout_width="fill";--宽度
          layout_height="198dp";--高度
          orientation="vertical";--重力
          {--卡片布局
            CardView;
            radius="55";--圆角
            elevation="0";--阴影
            layout_width="fill";--宽度
            layout_height="fill";--高度
            --layout_marginBottom="2.5%w";--底距
            CardBackgroundColor="#AEEEEEEE";
            {--◇主图
              ImageView;--图片控件
              layout_width="175dp";--宽度
              layout_height="fill";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background="https://txc.gtimg.com/data/292760/2024/0713/a71e8600432e1031ccd5b303357d86f3.webp";
            },--主图◇
            {--◇标题
              TextView;
              text="会下雨的生态缸";
              textSize="15sp";
              textColor="#FFFFFFFF";--颜色
              background='#60000000',--背景色
              layout_width="fill";--宽度
              layout_height="28dp";--高度
              --layout_margin="3.5dp";--边距
              layout_gravity="bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接="https://shop420102691.m.taobao.com/"})
            end;
          },--卡片布局
        },--C◆
        {--◆D
          CardView;--卡片控件
          radius="55";--圆角
          elevation="0";--阴影
          layout_width="fill";--宽度
          layout_height="255dp";--高度
          layout_marginBottom="2.5%w";--底距
          CardBackgroundColor="#AEEEEEEE";
          {--竖直布局
            LinearLayout;
            layout_width="fill";--宽度
            layout_height="fill";--高度
            orientation="vertical";--重力
            {--◇主图
              ImageView;--图片控件
              layout_width="170dp";--宽度
              layout_height="227dp";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background=图D;
            },--主图◇
            {--◇标题
              TextView;
              text=标D;
              textSize="15sp";
              textColor="#FF333333";
              layout_width="160dp";--宽度
              layout_margin="3.5dp";--边距
              layout_gravity="center|bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接=链D})
            end;
          },--竖直布局
        },--D◆
      },--◆左◆
      {--◆右◆
        LinearLayout;
        layout_weight="1";--权重
        layout_height="fill";--高度
        orientation="vertical";--重力
        layout_marginLeft="1.25%w";--左距
        {--◆E
          CardView;--卡片控件
          radius="55";--圆角
          elevation="0";--阴影
          layout_width="fill";--宽度
          layout_height="255dp";--高度
          layout_marginBottom="2.5%w";--底距
          CardBackgroundColor="#AEEEEEEE";
          {--竖直布局
            LinearLayout;
            layout_width="fill";--宽度
            layout_height="fill";--高度
            orientation="vertical";--重力
            {--◇主图
              ImageView;--图片控件
              layout_width="170dp";--宽度
              layout_height="227dp";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background=图E;
            },--主图◇
            {
              TextView;
              text=标E;
              textSize="15sp";
              textColor="#FF333333";
              layout_width="160dp";--宽度
              layout_margin="3.5dp";--边距
              layout_gravity="center|bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接=链E})
            end;
          },--竖直布局
        },--E◆
        {--◆F
          LinearLayout;
          layout_width="fill";--宽度
          layout_height="198dp";--高度
          orientation="vertical";--重力
          {--卡片布局
            CardView;
            radius="55";--圆角
            elevation="0";--阴影
            layout_width="fill";--宽度
            layout_height="fill";--高度
            --layout_marginBottom="2.5%w";--底距
            CardBackgroundColor="#AEEEEEEE";
            {--◇主图
              ImageView;--图片控件
              layout_width="175dp";--宽度
              layout_height="fill";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background="https://txc.gtimg.com/data/292760/2024/0713/a71e8600432e1031ccd5b303357d86f3.webp";
            },--主图◇
            {--◇标题
              TextView;
              text="会下雨的生态缸";
              textSize="15sp";
              textColor="#FFFFFFFF";--颜色
              background='#60000000',--背景色
              layout_width="fill";--宽度
              layout_height="28dp";--高度
              --layout_margin="3.5dp";--边距
              layout_gravity="bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接="https://shop420102691.m.taobao.com/"})
            end;
          },--卡片布局
        },--F◆
        {--◆G
          CardView;--卡片控件
          radius="55";--圆角
          elevation="0";--阴影
          layout_width="fill";--宽度
          layout_height="255dp";--高度
          layout_marginBottom="2.5%w";--底距
          CardBackgroundColor="#AEEEEEEE";
          {--竖直布局
            LinearLayout;
            layout_width="fill";--宽度
            layout_height="fill";--高度
            orientation="vertical";--重力
            {--◇主图
              ImageView;--图片控件
              layout_width="170dp";--宽度
              layout_height="227dp";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background=图G;
            },--主图◇
            {--◇标题
              TextView;
              text=标G;
              textSize="15sp";
              textColor="#FF333333";
              layout_width="160dp";--宽度
              layout_margin="3.5dp";--边距
              layout_gravity="center|bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接=链G})
            end;
          },--竖直布局
        },--G◆
        {--◆H
          LinearLayout;
          layout_width="fill";--宽度
          layout_height="198dp";--高度
          orientation="vertical";--重力
          {--卡片布局
            CardView;
            radius="55";--圆角
            elevation="0";--阴影
            layout_width="fill";--宽度
            layout_height="fill";--高度
            --layout_marginBottom="2.5%w";--底距
            CardBackgroundColor="#AEEEEEEE";
            {--◇主图
              ImageView;--图片控件
              layout_width="175dp";--宽度
              layout_height="fill";--高度
              layout_gravity="center|top";
              scaleType="fitXY";--图片显示类型
              background="https://txc.gtimg.com/data/292760/2024/0713/a71e8600432e1031ccd5b303357d86f3.webp";
            },--主图◇
            {--◇标题
              TextView;
              text="会下雨的生态缸";
              textSize="15sp";
              textColor="#FFFFFFFF";--颜色
              background='#60000000',--背景色
              layout_width="fill";--宽度
              layout_height="28dp";--高度
              --layout_margin="3.5dp";--边距
              layout_gravity="bottom";
              gravity="center";
            },--标题◇
            onClick=function()
              进入子页面("浏览器",{链接="https://shop420102691.m.taobao.com/"})
            end;
          },--卡片布局
        },--H◆
      },--◆右◆
    },--●广告●

  },--███全局竖向滑动███
},-1)
