xbj=--小广告位布局◆◆◆
{
  LinearLayout,
  orientation='vertical',--重力属性
  layout_width='fill',--布局宽度
  layout_height='130dp',--布局高度
  --background="#FFF5F5F5",--背景色▶
  {
    CardView,--卡片控件
    radius='12dp',--卡片圆角
    elevation='2dp',--阴影属性
    layout_marginTop='5dp';--顶距◆
    layout_margin='14dp',--卡片边距◆
    layout_height='122dp',--卡片高度◆
    layout_width='fill',--卡片宽度
    layout_gravity='center',--重力属性
    {
      ScrollView,--竖向滑动
      layout_width='fill',--宽度
      layout_height='fill',--高度
      {
        LinearLayout,
        orientation='vertical',--重力属性
        layout_width='fill',--宽度
        layout_height='fill',--高度
        {
          PageView,
          layout_width='fill',--宽度
          layout_height='122dp',--滑动长度◆
          layout_weight='1',
          id='xggw',--布局id
          pages={
            {--●1●
              LinearLayout,
              gravity='center',--重力
              layout_width='fill',--宽度
              layout_height='fill',--高度
              orientation='vertical',--重力
              background='#FFFAFAFA',--背景色
              id='tp1',--滑动id
              {
                CardView,--卡片控件
                layout_width='332dp',--图片宽度
                layout_height='match_parent',--图片高度
                {
                  ImageView,--图片控件
                  layout_height='fill',--图片高度
                  layout_width='fill',--图片宽度
                  scaleType='fitXY',--图片显示类型
                  background='https://txc.gtimg.com/data/292760/2023/0628/79c43e9615118a59f2d1985df12f050d.jpeg',--背景颜色(图片路径)
                },
                {
                  TextView,
                  textSize='15sp',--大小
                  gravity='center',--文字重力
                  textColor='#FFFFFFFF',--颜色
                  background='#44000000',--背景色
                  layout_gravity='bottom',--方框重力
                  layout_width='match_parent',--宽度
                  layout_height='30dp',--高度
                  text='留声机用户福利，联系店铺客服打6折！！',--文字◆
                },
              },
            },
            {--●2●
              LinearLayout,
              gravity='center',--重力
              layout_width='fill',--宽度
              layout_height='fill',--高度
              orientation='vertical',--重力
              background='#FFFAFAFA',--背景色
              id='tp2',--滑动id
              {
                CardView,--卡片控件
                layout_width='332dp',--图片宽度
                layout_height='match_parent',--图片高度
                {
                  ImageView,--图片控件
                  layout_height='fill',--图片高度
                  layout_width='fill',--图片宽度
                  scaleType='fitXY',--图片显示类型
                  background='https://txc.gtimg.com/data/292760/2021/1019/35b92f5e10b2a4d1e782d78169d3d219.png',--背景颜色(图片路径)
                },
                {
                  TextView,
                  textSize='15sp',--大小
                  gravity='center',--文字重力
                  textColor='#FFFFFFFF',--颜色
                  background='#44000000',--背景色
                  layout_gravity='bottom',--方框重力
                  layout_width='match_parent',--宽度
                  layout_height='30dp',--高度
                  text='APP新手帮助，软件不会用的的看这里！！',--文字◆
                },
              },
            },
            {--●3●
              LinearLayout,
              gravity='center',--重力
              layout_width='fill',--宽度
              layout_height='fill',--高度
              orientation='vertical',--重力
              background='#FFFAFAFA',--背景色
              id='tp3',--滑动id
              {
                CardView,--卡片控件
                layout_width='332dp',--图片宽度
                layout_height='match_parent',--图片高度
                {
                  ImageView,--图片控件
                  layout_height='fill',--图片高度
                  layout_width='fill',--图片宽度
                  scaleType='fitXY',--图片显示类型
                  background='https://txc.gtimg.com/data/292760/2021/1019/1d3430b39d8717971a5f512bd76e1354.png',--背景颜色(图片路径)
                },
                {
                  TextView,
                  textSize='15sp',--大小
                  gravity='center',--文字重力
                  textColor='#FFFFFFFF',--颜色
                  background='#44000000',--背景色
                  layout_gravity='bottom',--方框重力
                  layout_width='match_parent',--宽度
                  layout_height='30dp',--高度
                  text='网购隐藏优惠低价捡漏，不薅羊毛是傻瓜！',--文字◆
                },
              },
            }
            --结束◆◆

          },
        },
      },

    },
  },
}
webView.addView(loadlayout(xbj))--网络幽灵


--自动滑动图片◆◆
tp1.onClick=function()--●1●
  import "android.content.Intent"
  import "android.net.Uri"
  url="https://shop221504625.taobao.com"
  viewIntent = Intent("android.intent.action.VIEW",Uri.parse(url))
  activity.startActivity(viewIntent)
end--结束
tp2.onClick=function()--●2●
  xggw.showPage(1)--序号◆
  进入子页面("社区",{标题="APP新手帮助",链接="https://support.qq.com/embed/phone/374133/faqs-more/"})
  弹出消息("若加载较慢 可点击左上角按钮刷新")
end--结束
tp3.onClick=function()--●3●
  xggw.showPage(2)--序号◆
  进入子页面("羊毛")
end--结束


--设置图片停留时间◆◆
local n=0 
function xjt()--小广告位监听
  task(3500,function()--3.5秒滑动一次◆
    n=n+1 xggw.showPage(n%3)--3张图片◆
    xjt()
  end)
end 
xjt()




--[[通知开始◆◆◆
drawerLayout.getChildAt(0).addView(loadlayout{
  LinearLayout,
  orientation='vertical',--重力属性
  layout_width='fill',--布局宽度
  layout_height='fill',--布局高度
  {
    LinearLayout,
    orientation="horizontal",
    layout_width="fill";--宽度
    layout_height="21.3%w";--高度
    gravity='left',--重力属性center
    background="#FFFFFFFF",--顶部颜色

    {--标题◆
      TextView;
      text="留声机",
      textSize="17sp";
      textColor="#FF040404";
      layout_gravity="center",
      layout_marginLeft="5%w";--左距
      layout_marginTop="3.8%w";--顶距",
    };

    {--通知◆
      CardView,
      id="tz",
      layout_width="60%w",--宽度
      layout_height="8%w",--高度
      radius="100%w",--圆角弧度
      elevation="100%w",--圆角弧度
      layout_marginLeft='5%w';--左距
      layout_marginTop="10.5%w";--顶距3.8
      CardBackgroundColor="#09000000",--颜色--透明80FFFFFF
      clickable=true,
      focusable=true,
      {
        ImageView,
        layout_marginLeft="0.65%w";
        layout_width="24dp",--按钮尺寸
        layout_height="24dp",--按钮尺寸
        layout_marginTop="0.9%w";--顶距",
        ColorFilter="#FF757575";--图片蒙版
        src="drawable/1_tz.png",--按钮路径◆
      };
      {
        TextView;--文本控件
        --layout_marginRight="35%w",--布局右距
        layout_marginLeft="8%w",--布局左距
        gravity='center';--重力
        --左:left 右:right 中:center 顶:top 底:bottom
        layout_width='fill';--宽度
        layout_height='fill';--高度
        singleLine=true;--单行显示
        ellipsize="marquee",--显示     
        Selected=true;--显示
        textColor='#FF757575';--文字颜色       
        text='留声机尝鲜版发布啦，点此可下载，欢迎大家体验~';--显示文字
        textSize='16dp';--文字大小
      };
    },

    {--退出◆
      ImageView,
      id="tc",
      layout_marginLeft="5%w";--左距
      layout_width="22dp",--按钮尺寸
      layout_height="22dp",--按钮尺寸
      layout_gravity="center|right",
      layout_marginTop="4%w";--顶距",
      src="drawable/close_circle.png",--按钮路径◆
    };

  },
},-1)

--点击◆◆
tz.onClick=function()
  进入子页面("浏览器",{标题="留声机APP【请更新】",链接="https://sneer.lanzoui.com/b06s2z42d"})
end
tc.onClick=function()
  退出页面()
end--点击◆◆]]
